
import { Providers } from "@/Global/provider";
import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body
        
      >
        {/* Navigation */}
        <nav
          className="bg-gray-800 text-white p-4 flex gap-x-4 justify-center"
        >
          <Link href="/">Home</Link>
          <Link href="/products">Products</Link>
          <Link href="/cart" className="ml-auto">Cart</Link>
        </nav>
        {/* End of Navigation */}
        {/* <Provider store={store}> */}
        <Providers>{children}</Providers>
        {/* </Provider> */}
      </body>
    </html>
  );
}
